spring:
  datasource:
    username: root #${USER_NAME}
    hikari:
      maximum-pool-size: 5 #"${spring.datasource.hikari.maximum-pool-size}"
      connection-timeout: 20000 #"${spring.datasource.hikari.connection-timeout}"
    url: jdbc:mysql://localhost:3306/rol-db #${URL_DB_USER}
    password: admin #${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
