spring:
  datasource:
    username: ${USER_NAME}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
      connection-timeout: ${spring.datasource.hikari.connection-timeout}
    url: ${URL}
    password: ${PASSWORD}
