server:
  servlet:
    context-path: /user-api
  port: 0 #${PORT}

spring:
  application:
    name: usuarios
  profiles:
    active: dev #${PROFILE}
  messages:
    basename: messages, messages-error
    encoding: utf-8

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #${URL_EUREKA}

